#define AIN1_SEL ANSA0
#define AIN1_CH 0
#define AIN3_SEL ANSA1
#define AIN3_CH 1
#define AIN4_SEL ANSA3
#define AIN4_CH 3
#define AIN5_SEL ANSB3
#define AIN5_CH 9
#define AIN7_SEL ANSA5
#define AIN7_CH 5